# Notice, this file depends upon the 'nginx-proxy' network, the 'nginx-proxy' container,
# and the 'letsencrypt' container existing from the following docker-compose file
#
# https://github.com/polterguy/magic.deploy/blob/master/docker-compose.yml
#
# Hence, this file will only be deployable unchanged on a VPS where you have already deployed
# Magic from before.
#
# If you don't want this, you'll need to pull in the 'nginx-proxy' and 'letsencrypt' containers
# from the above file, to make sure you're correctly setting up the nGinx reverse proxy, and
# the LetsEncrypt cerificate retriever container.

version: '2'

services:
  # Your app's main container
  babelmail:
    container_name: babelmail
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      # REPLACE THESE NEXT 3 PARTS WITH YOUR OWN DOMAIN/EMAIL
      - VIRTUAL_HOST=frontend.yourdomain.com
      - LETSENCRYPT_HOST=frontend.yourdomain.com
      - LETSENCRYPT_EMAIL=your_name@yourdomain.no

    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
