/*
 * Automatically generated by Magic
 */

import { Component, OnInit, ViewChild } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { GridComponent } from '@app/base/grid.component';
import { MatPaginator } from '@angular/material/paginator';
import { MatDialog } from '@angular/material/dialog';
import { FormControl } from '@angular/forms';

import { EditBabelmail_attachments_attachmentsComponent } from './modals/edit.babelmail_attachments_attachments.component';
import { HttpService } from 'src/app/services/http-service';
import { AuthService } from 'src/app/services/auth-service';
import { environment } from '@env/environment';

/**
 * "Datagrid" component for displaying instance of Attachments
 * entities from your HTTP REST backend.
 */
@Component({
  selector: 'app-babelmail_attachments_attachments',
  templateUrl: './babelmail_attachments_attachments.component.html',
  styleUrls: ['./babelmail_attachments_attachments.component.scss'],
})
export class Babelmail_attachments_attachmentsComponent
  extends GridComponent
  implements OnInit
{
  /**
   * Which columns we should display. Reorder to prioritize columns differently.
   * Notice! 'delete-instance' should always come last.
   */
  public displayedColumns: string[] = [
    'filename',
    'email_id',
    'delete-instance',
  ];

  // Need to view paginator as a child to update page index of it.
  @ViewChild(MatPaginator, { static: true }) paginator: MatPaginator;

  // Form control declarations to bind up with reactive form elements.
  public filename: FormControl;
  public id: FormControl;
  public email_id: FormControl;
  public path: FormControl;

  /**
   * Creates an instance of your CRUD component.
   *
   * @param httpService Needed to be able to invoke backend during CRUD operations
   * @param authService Needed to check if user has access to invoking CRUD operation
   * @param snackBar Needed to display errror and feedback
   * @param dialog Needed to show modal dialog as user edits or creates new entities
   */
  constructor(
    public httpService: HttpService,
    public authService: AuthService,
    protected snackBar: MatSnackBar,
    protected dialog: MatDialog
  ) {
    super(authService, snackBar, dialog);
  }

  /**
   * Overridde abstract method necessary to return the URL endpoint
   * for CRUD methods to base class.
   */
  public url() {
    return 'magic/modules/babelmail/attachments/attachments';
  }

  /**
   * Invoked when user wants to download an attachment.
   *
   * @param el File to download
   */
  public download(el: any) {
    const splits = el.path.split('.');
    window.location.href =
      environment.apiUrl +
      'magic/modules/babelmail/files/download-file?file=' +
      encodeURIComponent(el.path) +
      '&filename=' +
      el.filename +
      '.' +
      splits[splits.length - 1];
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually retrieve items from backend.
   */
  protected read(filter: any) {
    return this.httpService.babelmail_attachments_attachments.read(filter);
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually retrieve count of items from backend.
   */
  protected count(filter: any) {
    return this.httpService.babelmail_attachments_attachments.count(filter);
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually delete items in backend.
   */
  protected delete(ids: any) {
    return this.httpService.babelmail_attachments_attachments.delete(ids);
  }

  /**
   * Implementation of abstract base class method, to reset paginator
   * of component.
   */
  protected resetPaginator() {
    this.paginator.pageIndex = 0;
    this.filter.offset = 0;
  }

  /**
   * OnInit implementation. Retrieves initial data (unfiltered),
   * and instantiates our FormControls.
   */
  public ngOnInit() {
    // Retrieves data from our backend, unfiltered, and binds our mat-table accordingly.
    this.getData();

    /*
     * Creating our filtering FormControl instances, which gives us "live filtering"
     * on our columns.
     */
    this.filename = this.createFormControl('filename.like');
    this.id = this.createFormControl('id.eq');
    this.email_id = this.createFormControl('email_id.eq');
    this.path = this.createFormControl('path.eq');
  }

  /**
   * Invoked when user wants to edit an entity
   *
   * This will show a modal dialog, allowing the user to edit his record.
   */
  public editEntity(entity: any) {
    const dialogRef = this.dialog.open(
      EditBabelmail_attachments_attachmentsComponent,
      {
        data: this.getEditData(entity),
      }
    );
    dialogRef.afterClosed().subscribe((res) => {
      if (res) {
        this.setEditData(res, entity);
      }
    });
  }

  /**
   * Invoked when user wants to create a new entity
   *
   * This will show a modal dialog, allowing the user to supply
   * the initial data for the entity.
   */
  public createEntity() {
    const dialogRef = this.dialog.open(
      EditBabelmail_attachments_attachmentsComponent,
      {
        data: {
          isEdit: false,
          entity: {},
        },
      }
    );
    dialogRef.afterClosed().subscribe((res: any) => {
      if (res) {
        this.itemCreated(res);
      }
    });
  }
}
