/*
 * Automatically generated by Magic
 */

import { throwError } from 'rxjs';
import { Component, Inject } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { HttpService } from 'src/app/services/http-service';
import { DialogComponent, DialogData } from '@app/base/dialog.component';

/**
 * Modal dialog for editing your existing Emails entity types, and/or
 * creating new entity types of type Emails.
 */
@Component({
  templateUrl: './edit.babelmail_emails_emails.component.html',
})
export class EditBabelmail_emails_emailsComponent extends DialogComponent {
  /**
   * Constructor taking a bunch of services injected using dependency injection.
   */
  constructor(
    public dialogRef: MatDialogRef<EditBabelmail_emails_emailsComponent>,
    @Inject(MAT_DIALOG_DATA) public data: DialogData,
    protected snackBar: MatSnackBar,
    public service: HttpService
  ) {
    super(snackBar);
    this.primaryKeys = [];
    this.createColumns = [
      'to_name',
      'from_name',
      'to_email',
      'from_email',
      'subject',
      'content',
      'language',
      'send',
      'html',
    ];
    this.updateColumns = [
      'to_name',
      'from_name',
      'to_email',
      'from_email',
      'subject',
      'content',
      'language',
      'id',
      'send',
      'html',
    ];
  }

  /**
   * Returns a reference to ths DialogData that was dependency injected
   * into component during creation.
   */
  protected getData() {
    return this.data;
  }

  /**
   * Returns a reference to the update method, to update entity.
   */
  protected getUpdateMethod() {
    return this.service.babelmail_emails_emails.update(this.data.entity);
  }
  /**
   * Returns a reference to the create method, to create new entities.
   */
  protected getCreateMethod() {
    return this.service.babelmail_emails_emails.create(this.data.entity);
  }

  /**
   * Closes dialog.
   *
   * @param data Entity that was created or updated
   */
  public close(data: any) {
    if (data) {
      this.dialogRef.close(data);
    } else {
      this.dialogRef.close();
    }
  }
}
