/*
 * Automatically generated by Magic
 */

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { TranslateModule } from '@ngx-translate/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MaterialModule } from './material.module';
import { NgxImageCompressService } from 'ngx-image-compress';

import { CoreModule } from '@core';
import { SharedModule } from '@shared';
import { AuthModule } from '@app/auth';
import { HomeModule } from './home/home.module';
import { ShellModule } from './shell/shell.module';
import { AppComponent } from './app.component';
import { MagicSelectorComponent } from './helpers/magic-selector/magic-selector.component';
import { MagicAutocompleteComponent } from './helpers/magic-autocomplete/magic-autocomplete.component';
import { MagicFilterComponent } from './helpers/magic-filter/magic-filter.component';
import { MagicImageComponent } from './helpers/magic-image/magic-image.component';
import { MagicImageViewComponent } from './helpers/magic-image-view/magic-image-view.component';
import { MagicFileViewComponent } from './helpers/magic-file-view/magic-file-view.component';
import { MagicFileComponent } from './helpers/magic-file/magic-file.component';
import { AppRoutingModule } from './app-routing.module';
import { environment } from '@env/environment';
import { JwtModule } from '@auth0/angular-jwt';
import {
  OwlDateTimeModule,
  OwlNativeDateTimeModule,
} from '@danielmoncada/angular-datetime-picker';
import { FormatDatePipe } from './pipes/format-date-pipe';
import { DateSincePipe } from './pipes/date-since.pipe';
import { ConfirmDialogComponent } from './confirm-deletion-dialog/confirm-dialog.component';

// Generated CRUD components here.
import { Babelmail_attachments_attachmentsComponent } from './components/babelmail/attachments/attachments/babelmail_attachments_attachments.component';
import { EditBabelmail_attachments_attachmentsComponent } from './components/babelmail/attachments/attachments/modals/edit.babelmail_attachments_attachments.component';
import { Babelmail_emails_emailsComponent } from './components/babelmail/emails/emails/babelmail_emails_emails.component';
import { EditBabelmail_emails_emailsComponent } from './components/babelmail/emails/emails/modals/edit.babelmail_emails_emails.component';
import { Babelmail_templates_templatesComponent } from './components/babelmail/templates/templates/babelmail_templates_templates.component';
import { EditBabelmail_templates_templatesComponent } from './components/babelmail/templates/templates/modals/edit.babelmail_templates_templates.component';

@NgModule({
  imports: [
    OwlDateTimeModule,
    OwlNativeDateTimeModule,
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    TranslateModule.forRoot(),
    BrowserAnimationsModule,
    MaterialModule,
    CoreModule,
    SharedModule,
    ShellModule,
    HomeModule,
    AuthModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          const persisted =
            sessionStorage.getItem('credentials') ||
            localStorage.getItem('credentials');
          if (persisted) {
            return JSON.parse(persisted).token;
          }
          return null;
        },
        allowedDomains: [environment.apiDomain],
      },
    }),
    AppRoutingModule, // must be imported as the last module as it contains the fallback route
  ],
  declarations: [
    AppComponent,
    MagicSelectorComponent,
    MagicAutocompleteComponent,
    MagicFilterComponent,
    MagicImageComponent,
    MagicImageViewComponent,
    MagicFileViewComponent,
    MagicFileComponent,
    FormatDatePipe,
    DateSincePipe,
    ConfirmDialogComponent,

    // Generated CRUD components here.
    Babelmail_attachments_attachmentsComponent,
    EditBabelmail_attachments_attachmentsComponent,
    Babelmail_emails_emailsComponent,
    EditBabelmail_emails_emailsComponent,
    Babelmail_templates_templatesComponent,
    EditBabelmail_templates_templatesComponent,
  ],

  providers: [NgxImageCompressService],
  bootstrap: [AppComponent],
})
export class AppModule {}
