/*
 * Automatically generated by Magic
 */

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { HomeComponent } from './home.component';
import { Shell } from '@app/shell/shell.service';

// Then importing all CRUD components.
import { Babelmail_attachments_attachmentsComponent } from '../components/babelmail/attachments/attachments/babelmail_attachments_attachments.component';
import { Babelmail_emails_emailsComponent } from '../components/babelmail/emails/emails/babelmail_emails_emails.component';
import { Babelmail_templates_templatesComponent } from '../components/babelmail/templates/templates/babelmail_templates_templates.component';

const routes: Routes = [
  Shell.childRoutes([
    { path: '', component: HomeComponent, data: { title: marker('Home') } },

    // Then routes for all CRUD components.
    {
      path: 'crud/babelmail/attachments/attachments',
      component: Babelmail_attachments_attachmentsComponent,
      data: { title: marker('babelmail/attachments/attachments') },
    },
    {
      path: 'crud/babelmail/emails/emails',
      component: Babelmail_emails_emailsComponent,
      data: { title: marker('babelmail/emails/emails') },
    },
    {
      path: 'crud/babelmail/templates/templates',
      component: Babelmail_templates_templatesComponent,
      data: { title: marker('babelmail/templates/templates') },
    },
  ]),
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: [],
})
export class HomeRoutingModule {}
